"""add_alerts_table

Revision ID: baf6ee849f28
Revises: 2e2448582166
Create Date: 2026-03-08 11:19:02.197701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf6ee849f28'
down_revision: Union[str, Sequence[str], None] = '2e2448582166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('trigger_keyword', sa.String(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_trigger_keyword', 'alerts', ['trigger_keyword'], unique=False)
    op.create_index('ix_alerts_user_id', 'alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_user_id', table_name='alerts')
    op.drop_index('ix_alerts_trigger_keyword', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
