"""add_users_table

Revision ID: ec2d8fa923e7
Revises: baf6ee849f28
Create Date: 2026-03-08 12:20:39.888041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ec2d8fa923e7'
down_revision: Union[str, Sequence[str], None] = 'baf6ee849f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('explicit_interests', sa.Text(), nullable=False),
    sa.Column('implicit_weights', sa.Text(), nullable=False),
    sa.Column('alert_keywords', sa.Text(), nullable=False),
    sa.Column('notification_email', sa.String(length=320), nullable=False),
    sa.Column('digest_hour', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
